name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.1

    - name: Download Redigo Module
      run: cd ./backend && go mod download github.com/gomodule/redigo

    - name: Build Backend
      run: cd ./backend && go build

    - name: Build Frontend
      run: cd ./frontend && go build

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v3
    
    - name: Test Frontend
      run: cd ./frontend && go test
  Publish:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: Michael-AngeloK/simple-fortune-cookie

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
