name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.1

    - name: Download Redigo Module
      run: cd ./backend && go mod download github.com/gomodule/redigo

    - name: Build Backend
      run: cd ./backend && go build

    - name: Build Frontend
      run: cd ./frontend && go build

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v3
    
    - name: Test Frontend
      run: cd ./frontend && go test